services:
  seaweedfs:
    image: chrislusf/seaweedfs:4.20
    container_name: logiflow_s3_storage
    ports:
      - "8333:8333"
    command: "mini -dir=/data"
    volumes:
      - s3_data:/data
    restart: unless-stopped

  s3-init:
      image: amazon/aws-cli
      container_name: logiflow_s3_init
      depends_on:
        - seaweedfs
      volumes:
        - ./policy.json:/tmp/policy.json
      entrypoint: [ "/bin/sh", "-c" ]
      command: >
        "
        sleep 5;
        aws --endpoint-url http://seaweedfs:8333 s3 mb s3://public-images;
        aws --endpoint-url http://seaweedfs:8333 s3api put-bucket-policy --bucket public-images --policy file:///tmp/policy.json;
        echo 'S3 Bucket initialized successfully!';
        "
volumes:
  s3_data:
