version: '3.8'

services:
  frontend:
    build: .
    container_name: logiflow_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - seaweedfs

  seaweedfs:
    image: chrislusf/seaweedfs:latest
    container_name: logiflow_s3_storage
    ports:
      - "8333:8333"
      - "9333:9333"
    command: "server -dir=/data -s3"
    volumes:
      - ./infra/s3-data:/data
    restart: unless-stopped
