export const AUTH = {
  login: {
    title: 'Log in',
    emailLabel: 'Email Address',
    emailPlaceholder: 'user@gmail.com',
    passwordLabel: 'Password',
    passwordPlaceholder: '*******',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot Password?',
    submitBtn: 'Log In',
    submitBtnLoading: 'Logging in...',
    noAccount: 'No account yet?',
    signUp: 'Sign Up',
    success: 'Successfully logged in!',
  },
  register: {
    title: 'Create an account',
    subtitle: 'Join LogiFlow to manage your fleet efficiently.',
    fullNameLabel: 'Full Name',
    fullNamePlaceholder: 'Full Name',
    emailLabel: 'Email Address',
    emailPlaceholder: 'user@gmail.com',
    phoneLabel: 'Phone Number',
    phonePlaceholder: '+380991234567',
    roleLabel: 'Select Role',
    passwordLabel: 'Password',
    passwordPlaceholder: 'Min. 8 characters',
    confirmPasswordLabel: 'Confirm Password',
    confirmPasswordPlaceholder: 'Repeat password',
    submitBtn: 'Create Account',
    submitBtnLoading: 'Creating Account...',
    alreadyHaveAccount: 'Already have an account?',
    logIn: 'Log In',
    success: 'Registration successful! You can now log in.',
  },
  roles: {
    client: 'Sender',
    manager: 'Manager',
    driver: 'Driver',
  },
  errors: {
    emailRequired: 'Email is required',
    emailInvalid: 'Invalid email format',
    passwordRequired: 'Password is required',
    passwordMinLength: 'Password must be at least 8 characters',
    fullNameRequired: 'Full name is required',
    phoneRequired: 'Phone number is required',
    phoneInvalid: 'Invalid phone format (e.g. +380991234567)',
    roleRequired: 'Please select a role',
    confirmPasswordRequired: 'Please confirm your password',
    passwordsMismatch: 'Passwords do not match',
    fillRequired: 'Please fill all the required fields.',
  },
}
